include:
  - auth_service/docker-compose.yaml

version: '3.9'
services:
  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - 5672
    ports:
      - "15672:15672"
    networks:
      - cdn_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: 'cdn_rabbit'

  worker-app:
    build:
      dockerfile: ./workers/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8003
    command: /bin/sh -c 'faststream run main:app'
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - cdn_network
    container_name: 'cdn_worker'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ./.env
    command: server --console-address ":9001" /data
    networks:
      - cdn_network
    container_name: 'cdn_minio'

  postgres:
    image: postgres:16
    container_name: cdn_postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    networks:
      - cdn_network

  nginx-backend:
    image: nginx:1.25.3
    container_name: 'cdn_nginx_backend'
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
      - auth-api
      - hls-api
    networks:
      - cdn_network

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    container_name: 'cdn_nginx_frontend'
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - cdn_network

  hls-api:
    build:
      dockerfile: ./hls_service/src/Dockerfile
      context: .
    container_name: 'cdn_hls_api'
    env_file:
      - .env
    expose:
      - 8002
    networks:
      - cdn_network

volumes:
  minio_storage:
  postgres_vol:


networks:
  cdn_network:
    driver: bridge