include:
  - auth_service/docker-compose.yaml

services:
  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - 5672
    ports:
      - "15672:15672"
    networks:
      - cdn_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: 'cdn_rabbit'

  worker-app:
    build:
      dockerfile: ./workers/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8003
    command: /bin/sh -c 'faststream run main:app'
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - cdn_network
    container_name: 'cdn_worker'

  minio-main:
    image: minio/minio
    container_name: cdn_minio_main
    volumes:
      - data_minio_main:/data
    env_file:
      - ./.env
    command: server --console-address ':9001' http://minio-main/data http://minio-cdn1/data http://minio-cdn2/data
    expose:
      - 9000
    networks:
      - cdn_network

  minio-cdn1:
    image: minio/minio
    container_name: cdn_minio_cdn1
    volumes:
      - data_minio_cdn1:/data
    env_file:
      - ./.env
    command: server --console-address ':9001' http://minio-main/data http://minio-cdn1/data http://minio-cdn2/data
    expose:
      - 9000
    networks:
      - cdn_network

  minio-cdn2:
    image: minio/minio
    container_name: cdn_minio_cdn2
    volumes:
      - data_minio_cdn2:/data
    env_file:
      - ./.env
    command: server --console-address ':9001' http://minio-main/data http://minio-cdn1/data http://minio-cdn2/data
    expose:
      - 9000
    networks:
      - cdn_network

  nginx-backend:
    image: nginx:1.25.3
    container_name: 'cdn_nginx_backend'
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/services.conf:/etc/nginx/conf.d/services.conf:ro
      - ./nginx/GeoIP.dat:/etc/nginx/geoip/GeoIP.dat:ro
      - static_value:/data/static
      - media_value:/data/media
    depends_on:
      - minio-main
      - minio-cdn1
      - minio-cdn2
      - auth-api
      - hls-api
      - admin_panel
    networks:
      - cdn_network

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    container_name: 'cdn_nginx_frontend'
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio-main
    networks:
      - cdn_network

  hls-api:
    build:
      dockerfile: ./hls_service/src/Dockerfile
      context: .
    container_name: 'cdn_hls_api'
    env_file:
      - .env
    expose:
      - 8002
    networks:
      - cdn_network

  admin_panel:
    build:
      context: ./admin_panel/src
      dockerfile: Dockerfile
    container_name: cdn_admin_panel
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbit
      - celery
      - minio-main
    networks:
      - cdn_network
    volumes:
      - ./admin_panel/src:/app
      - static_value:/static/ #app
      - media_value:/app/media/

  postgres:
    image: postgres:16
    container_name: cdn_postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    networks:
      - cdn_network

  celery:
    build:
      context: ./admin_panel/src
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=DEBUG
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./admin_panel/src:/app
    env_file:
      - .env
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - cdn_network

volumes:
  static_value:
  media_value:
  postgres_vol:
  data_minio_main:
  data_minio_cdn1:
  data_minio_cdn2:

networks:
  cdn_network:
    driver: bridge