services:
  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - 5672
    ports:
      - "15672:15672"
    networks:
      - cdn_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: 'cdn_rabbit'

  worker-app:
    build:
      dockerfile: ./workers/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8003
    command: /bin/sh -c 'faststream run main:app'
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - cdn_network
    container_name: 'cdn_worker'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ./.env
    command: server --console-address ":9001" /data
    networks:
      - cdn_network
    container_name: 'cdn_minio'

volumes:
  minio_storage:

networks:
  cdn_network:
    driver: bridge