services:
  auth_api:
    ports:
      - "8000:8000"
    #command: uvicorn src.main:app --reload --host $SERVICE_HOST --port $SERVICE_PORT

  auth_postgres:
    ports:
      - "5432:5432"

  auth_redis:
    ports:
      - "6379:6379"


volumes:
  postgres_data_auth:
  redis_data:

networks:
  cdn_network:
    driver: bridge
